pipeline {
   agent any
   environment {
       // repository name must be lowercase
       registry = "jettgu/k8s_cicd_goLang_helloworld"
       GOCACHE = "/tmp"
   }
   stages {
       stage('Build') {
           agent {
               docker {
                   image 'golang'
               }
           }
           steps {
               // Create our project directory.
               sh 'cd ${GOPATH}/src'
               sh 'mkdir -p ${GOPATH}/src/hello-world'
               // Copy all files in our Jenkins workspace to our project directory.
               sh 'cp -r ${WORKSPACE}/helloworld/main.go ${GOPATH}/src/hello-world/'
               // Build the app.
               sh 'go build hello-world'
           }
       }
       stage('Test') {
           agent {
               docker {
                   image 'golang'
               }
           }
           steps {
               // Create our project directory.
               sh 'cd ${GOPATH}/src'
               sh 'mkdir -p ${GOPATH}/src/hello-world'
               // Copy all files in our Jenkins workspace to our project directory.
               sh 'cp -r ${WORKSPACE}/helloworld/main_test.go ${GOPATH}/src/hello-world'
               // sh 'rm -f ${GOPATH}/src/hello-world/main.go'
               // Remove cached test results.
               sh 'go clean -cache'
               // Run Unit Tests.
               sh 'go test hello-world -v -short'
           }
       }
       stage('Publish') {
           environment {
               registryCredential = 'DockerHub'
           }
           steps{
               script {
                   // def appimage = docker.build (registry + ":$BUILD_NUMBER", "-f ${dockerfile} .")
                   def appimage = ''
                   dir("${WORKSPACE}/helloworld"){
                       // appimage = docker.build(registry + ":$BUILD_NUMBER", "-f ${dockerfile} .")
                       appimage = docker.build(registry + ":$BUILD_NUMBER")
                   }

                   docker.withRegistry( '', registryCredential ) {
                       appimage.push()
                       appimage.push('latest')
                   }
               }
           }
       }
       stage ('Deploy') {
           steps {
               script{
                   def image_id = registry + ":$BUILD_NUMBER"
                   sh "ansible-playbook  helloworld/playbook.yml --extra-vars \"image_id=${image_id}\""
               }
           }
       }
   }
}
