- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      src: K8s_service.yml
      #definition: ""
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      #definition: ""
      #src: K8s_deployment.yml
      #below variable $image_id is used in K8s_deployment.yml, and second image_id parameter will be passed on command line
      definition: "{{ lookup('template', 'K8s_deployment.yml') | regex_replace('\\$image_id', image_id) }}"
